name: News
on:
  push:
    branches:
      - '*'
  release:
    types:
      - created
jobs:
  changelog:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: "✏️ Generate news"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sinceTag: v0.1.2
          headerLabel: '# History of user-visible changes'
          output: NEWS.md
          base: HISTORY.md
          issues: no
#          futureRelease: v0.3.1

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update NEWS.md
          file_pattern: NEWS.md
